# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1.4

FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts && npm run build

# Final stage
FROM node:lts-alpine
WORKDIR /app

# Copy built files and production deps
COPY --from=builder /app/build ./build
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Ensure build script is executable
RUN chmod +x build/index.js

ENTRYPOINT ["node", "build/index.js"]
